name: Terraform Apply

on:
  workflow_dispatch:

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Create Public Access Key
        run: echo "${{ secrets.PUBLIC_ACCESS_KEY }}" > remote-host-control.pub

      - name: Install Terraform
        env:
          TERRAFORM_VERSION: "1.10.5"
        run: |
          tf_version=$TERRAFORM_VERSION
          wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
          unzip terraform_"$tf_version"_linux_amd64.zip
          sudo mv terraform /usr/local/bin/

      - name: Verify Terraform version
        run: terraform --version

      - name: Terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init -input=false

      - name: Terraform validation
        run: terraform validate

      - name: Terraform apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve -input=false

      - name: Get EC2 DNS
        id: get_dns
        run: |
          EC2_DNS=$(terraform output -raw server_public_dns)
          echo "EC2_DNS=$EC2_DNS" >> $GITHUB_ENV
          echo "::set-output name=ec2_dns::$EC2_DNS"

      - name: Trigger EC2 Config Workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: 02-EC2-Config.yml
          ref: main
          inputs: |
            ec2_dns: ${{ env.EC2_DNS }}
