name: Terraform Apply

on:
  workflow_dispatch:

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Create Public Access Key
        run: echo "${{ secrets.PUBLIC_ACCESS_KEY }}" > remote-host-control.pub

      - name: Install Terraform
        env:
          TERRAFORM_VERSION: "1.10.5"
        run: |
          tf_version=$TERRAFORM_VERSION
          wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
          unzip terraform_"$tf_version"_linux_amd64.zip
          sudo mv terraform /usr/local/bin/

      - name: Terraform version
        run: terraform --version

      - name: Terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate

      - name: Terraform apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve -input=false

      - name: Save EC2 DNS as artifact
        run: |
          terraform output -raw server_public_dns > ec2_dns.txt
        shell: bash

      - name: Upload DNS artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ec2-dns
          path: ec2_dns.txt

      - name: Trigger EC2 Config Workflow
        if: success()
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: 02-EC2-Config.yml
