name: EC2 Config

on:
  workflow_dispatch:

jobs:
  ec2_config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Download DNS artifact
        uses: actions/download-artifact@v3
        with:
          name: ec2-dns

      - name: Read EC2 DNS
        id: read_dns
        run: |
          EC2_HOST=$(cat ec2_dns.txt)
          echo "EC2_HOST=$EC2_HOST" >> $GITHUB_ENV

      - name: Config SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

      - name: Config AWS CLI on EC2
        run: |
          ssh -i private_key.pem ${{ secrets.EC2_USER }}@$EC2_HOST << 'EOF'
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set region us-east-1
            aws configure set output json
          EOF
