name: EC2 Config

on:
  workflow_dispatch:
    inputs:
      ec2_dns:
        description: 'EC2 DNS (public hostname or IP)'
        required: true

jobs:
  ec2_config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Config SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H ${{ github.event.inputs.ec2_dns }} >> ~/.ssh/known_hosts

      - name: Config AWS CLI on EC2
        run: |
          ssh -i private_key.pem ${{ secrets.EC2_USER }}@${{ github.event.inputs.ec2_dns }} << 'EOF'
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set region us-east-1
            aws configure set output json
          EOF
