name: 04 Deploy Project

on:
  workflow_dispatch:

jobs:
  create_eks_cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Config SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H $EC2_DNS >> ~/.ssh/known_hosts

      - name: Clone Repo And Execute Pods
        run: |
          ssh -i private_key.pem ${{ secrets.EC2_USER }}@$EC2_DNS << 'EOF'
            git clone https://github.com/dfbastidas/manifiestos
            kubectl apply -f manifiestos/manifiesto_nginx.yml
          EOF

      - name: Config Ingress Controller
        run: |
          ssh -i private_key.pem ${{ secrets.EC2_USER }}@$EC2_DNS << 'EOF'
            helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
            helm repo update
            helm install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace
            kubectl get pods -n ingress-nginx
            HOST=$(kubectl get svc ingress-nginx-controller -n ingress-nginx -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
            sed "s/\${REPLACE_ME}/$HOST/" manifiestos/manifiesto_ingress.yml > manifiestos/ingress.yml
            kubectl apply -f manifiestos/ingress.yml
          EOF