name: 99 Destroy project

on:
  workflow_dispatch:

jobs:
  create_eks_cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Create Public Access Key
        run: echo "${{ secrets.PUBLIC_ACCESS_KEY }}" > remote-host-control.pub

      - name: Install Terraform
        env:
          TERRAFORM_VERSION: "1.10.5"
        run: |
          tf_version=$TERRAFORM_VERSION
          wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
          unzip terraform_"$tf_version"_linux_amd64.zip
          sudo mv terraform /usr/local/bin/

      - name: Terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init -input=false

      - name: Get EC2 DNS from Terraform output
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        id: get_dns
        run: |
          EC2_DNS=$(terraform output -raw remote_k8s_host_public_dns)
          echo "EC2_DNS=$EC2_DNS" >> $GITHUB_ENV
          echo "::set-output name=ec2_dns::$EC2_DNS"

      - name: Config SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H $EC2_DNS >> ~/.ssh/known_hosts

      - name: Delete Pods
        run: |
          ssh -i private_key.pem ${{ secrets.EC2_USER }}@${{ env.EC2_DNS }} << 'EOF'
            kubectl delete -f manifiestos/manifiesto_nginx.yml
            kubectl delete -f manifiestos/ingress.yml
          EOF

      - name: Delete Nodes
        run: |
          ssh -i private_key.pem ${{ secrets.EC2_USER }}@${{ env.EC2_DNS }} << 'EOF'
            aws cloudformation delete-stack --stack-name eksctl-eks-mundos-e-nodegroup-workers-nodes
          EOF

      - name: Delete Cluster
        run: |
          ssh -i private_key.pem ${{ secrets.EC2_USER }}@${{ env.EC2_DNS }} << 'EOF'
            aws cloudformation delete-stack --stack-name eksctl-eks-mundos-e-cluster
          EOF

